name: ASV Controller
description: Custom sensros aggregation to control heating system for Home Assistant running on Raspberry Pi 4
version: 1.0.0
slug: asv-controller
arch:
  - aarch64
ports:
  35123/tcp: null
startup: application
boot: auto
init: false
options:
  test: "test string"
schema:
  test: str