name: ASV Controller
description: Custom sensros aggregation to control heating system for Home Assistant running on Raspberry Pi 4
version: 1.0.8
slug: asv-controller
arch:
  - aarch64
url: https://github.com/xirius/asv-controller-ha-addon
image: registry.asv-chauffage.be/avs/pi4-asv-controller
startup: application
boot: auto
init: false
map:
  - config
  - ssl
options:
  broker_host: "core-mosquitto"
  broker_port: 8883
  mqtt_username: "mqtt_user"
  mqtt_password: "mqtt_password"
  ssl_ca_file: "ca.crt"
  ssl_cert_file: "client.crt"
  ssl_key_file: "client.key"
  config_file: "asv-config.yaml"
schema:
  broker_host: str
  broker_port: int
  mqtt_username: str
  mqtt_password: str
  ssl_ca_file: str
  ssl_cert_file: str
  ssl_key_file: str
  config_file: str